### ISSUE TITLE
The "logging" module import is forgotten in "claimed/component-library/output/upload-to-cos.ipynb"

### ISSUE THREAD

**Issue by hassanrhanimi** [claimed-framework/claimed#172]
After using the claimed library for practicing purpose in a coursera course, i got this error "NameError: name ‘logging’ is not defined?" solved by importing this module in the "upload-to-cos.ipynb".

By the way thank you guys for the "Data Engineering and Machine Learning using Spark" course ;)

**Comment by romeokienzler** [comment]
[x] fixed in f4c5e59dab72d7bf4707294705fe2517e6fe0838 - thanks a lot!
