### ISSUE TITLE
notebook asset not showing

### ISSUE THREAD

**Issue by hkmr** [claimed-framework/claimed#32]
On Add to Project, the Notebook option is not showing.
So, how to add notebook to project.
![apache](https://user-images.githubusercontent.com/24650133/77246802-b3ec1b00-6c50-11ea-920a-a926dffc7297.png)

**Comment by romeokienzler** [comment]
please ask in the coursera discussion forum...not your fault - created an entry in the faq https://github.com/IBM/coursera/wiki/FAQ#i-dont-see-an-option-to-add-a-notebook
