### ISSUE TITLE
Watson Studio offers 50 execution hours per month

### ISSUE THREAD

**Issue by abhiray92** [claimed-framework/claimed#42]
@romeokienzler  I am unable to select the Free environment anymore on Watson Studio, for Notebooks. However, I get the error message "Watson Studio no longer offers free environments. Select another environment." while I try to open my previous notebooks created in the free Python instance.

**Comment by RekikAhmed** [comment]
Yes no more free version! So in the notebook you need to change your environment to the cheapest one ( like 1.5 per hour I guess) in order for it to run again.
What I am doing is use Colab.research.google.com (totally free) to try and mess around code, and Watson to submit, or try something that I won't need much time in.

**Comment by romeokienzler** [comment]
omg ... too bad...let me talk to the responsible folks...

**Comment by Shub123432** [comment]
Plz visit IBM clouds ..

**Comment by MohamedMetwally87** [comment]
@romeokienzler  yes plz i posted in the discussion panel on coursera but no one answered me, no it forces me to add my credit card either it sign me out

**Comment by stevemar** [comment]
Just clarifying things on this issue. [Watson Studio](https://cloud.ibm.com/catalog/services/watson-studio) offers a **Lite** plan that is free up to a limit of *50 capacity unit-hours per month*.

When creating a new notebook, choose the `Default Python 3.6 XS + DO (2 vCPU 8 GB RAM)` option. This runtime consumes 1 capacity unit per hour. It should leave you with 50 hours of execution time per month.

**Comment by romeokienzler** [comment]
This number got reduced to 20. That's why we send learners to https://labs.cognitiveclass.ai/ for "notebook only" work or also provide a way to directly use JupyterLab/Elyra from your computer:

docker run -it -v <your_project_folder_goes_here>:/home/jovyan/work -p 8888:8888 elyra/elyra
